### ISSUE TITLE
Implement: Honour `TestFile` from `PackageInfo` record

### ISSUE THREAD

**Issue by wilfwilson** [gap-actions/run-pkg-tests#13]
As mentioned in the code:
https://github.com/gap-actions/run-pkg-tests/blob/2f2aa4f6bca587dbdaddf69dd07b4d1225f0c9eb/action.yml#L43-L45

**Comment by fingolfin** [comment]
This was partially addressed in PR #16. What is left now is to remove the default value for `GAP_TESTFILE`
