### ISSUE TITLE
This action no longer works with GAP master branch and cygwin

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-actions/run-pkg-tests#27]
See:

https://github.com/semigroups/Semigroups/actions/runs/7420584539/job/20192252720?pr=969

It looks like the branch `cygwin-v2` hasn't be synced with `v2`, the diff contains (for example):
~~~
  ln -f -s $PWD /tmp/gaproot/pkg/

          # start GAP with custom GAP root, to ensure correct package version is loaded
-         GAP="$GAPROOT/gap -l /tmp/gaproot; --quitonbreak"
-
-         if ${{ inputs.only-needed }} = 'true' ; then
-           GAP="$GAP -A"
-         fi
+         GAP="$GAPROOT/bin/gap.sh -l /tmp/gaproot; --quitonbreak"
~~~

**Comment by fingolfin** [comment]
Argh! Thanks for the report and fix PR, James

**Comment by fingolfin** [comment]
This may affect other of our actions, I'll check them all now. (And I still would love to get rid of those `cygwin-v2` branches... in principle we should be able to do it via https://github.com/gap-actions/setup-gap/issues/18#issuecomment-1322385914 but someone has to find the time for it. Perhaps during the March GAP Days in Kaiserslautern or the August GAP Days in St Andrews?

**Comment by james-d-mitchell** [comment]
Good idea!

**Comment by fingolfin** [comment]
I've updated three affected actions, hopefully it works again now?

**Comment by james-d-mitchell** [comment]
Thanks @fingolfin I'm just re-running the failing job above, will post when that's complete.

**Comment by james-d-mitchell** [comment]
It worked now, thanks! @fingolfin
